# Generated by Django 3.1.2 on 2020-10-25 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='provider',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
